readme review and correction

diff --git a/0x14-mysql/5-mysql_backup b/0x14-mysql/5-mysql_backup
--- a/0x14-mysql/5-mysql_backup
+++ b/0x14-mysql/5-mysql_backup
@@ -1,5 +1,6 @@
 #!/usr/bin/env bash
 # Generates a MySQL dump and creates a compressed archive out of it
+
 # Set the MySQL root password as the first command-line argument
 mysql_root_password="$1"
 
@@ -9,6 +10,16 @@ mkdir "$backup_directory"
 
 # Export all databases using mysqldump and save it in the backup directory
 mysqldump -uroot -p"$mysql_root_password" --all-databases > "$backup_directory/backup.sql"
+
+# Restore the dump file to verify its validity
+mysql -uroot -p"$mysql_root_password" < "$backup_directory/backup.sql"
+restore_exit_code=$?
+
+if [ $restore_exit_code -eq 0 ]; then
+    echo "MySQL dump file restoration succeeded!"
+else
+    echo "MySQL dump file restoration failed!"
+fi
 
 # Create a tarball archive of the backup directory
 tar -czf "$backup_directory.tar.gz" "$backup_directory"
